name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create release package
        run: npm run pack.release

      - name: Get version from manifest
        id: version
        run: |
          echo "version=$(node -p "require('./manifest.json').version")" >> $GITHUB_OUTPUT
          echo "name=$(node -p "require('./manifest.json').name")" >> $GITHUB_OUTPUT
          echo "id=$(node -p "require('./manifest.json').id")" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            .packs/${{ steps.version.outputs.id }}-${{ steps.version.outputs.version }}/${{ steps.version.outputs.id }}-${{ steps.version.outputs.version }}.zip
            main.js
            manifest.json
          name: ${{ steps.version.outputs.name }} ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}